version: '3.8'
services:
  moondiffapp:
    build:
      context: .
    env_file:
      - env.dev
    volumes:
      - ./media:/app/media
      - ./db:/app/db

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./media:/app/media