version: '2'
services:
  moondiffapp:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 moondiff.wsgi --workers=4
    env_file:
      - ./env.dev

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
