# Generated by Django 4.2.2 on 2023-06-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pair",
            name="name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
