# Generated by Django 4.2.2 on 2023-07-01 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pair_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pair",
            unique_together=set(),
        ),
    ]
